using UnityEngine;

public class TorchPickup : MonoBehaviour
{
    public float pickupDistance = 3f; // distance maximale pour ramasser
    private Transform player;
    private bool playerInside = false;
    public GameObject interactionUI;

    public bool isCorrect = false;

    void Start()
    {
        // cherche le joueur dans la scène
        player = GameObject.FindGameObjectWithTag("Player").transform;
        
        interactionUI.SetActive(false);
    }

    void Update()
    {
        // clic gauche
        if (Input.GetMouseButtonDown(0))
        {
            TryPickup();
            if (playerInside = true)
            {
                isCorrect = false;
            }
            else
            {
                isCorrect = true;
            }
        }
    }

    // ReSharper disable Unity.PerformanceAnalysis
    void TryPickup()
    {
        if (player == null) return;

        float distance = Vector3.Distance(transform.position, player.position);

        if (distance <= pickupDistance)
        {
            TorchController playerTorch = FindObjectOfType<TorchController>();
            if (playerTorch != null)
            {
                playerTorch.GiveTorch();
            }
            
            Debug.Log("Torche ramassée !");
            Destroy(gameObject); // supprimer l’objet ramassé
            

        }
    }
    
    private void OnTriggerEnter(Collider other)
    {
        if (other.CompareTag("Player"))
        {
            playerInside = true;
            isCorrect = true;

            if (interactionUI != null)
                interactionUI.SetActive(true); // afficher le message
        }
    }

    private void OnTriggerExit(Collider other)
    {
        if (other.CompareTag("Player"))
        {
            playerInside = false;
            isCorrect = false;

            if (interactionUI != null)
                interactionUI.SetActive(false); // cacher le message
        }
    }
    
}